define([
'./texturizerOptions',
'./texturizerUtils',
'./texturizerUi',
'./render/_texturizer',
'./render/texturizerBox',
'./render/texturizerExplode',
'./render/texturizerStackedBars',
'./render/texturizerSineWave',
'./render/texturizerRegPoly',
'./render/texturizerIregPoly',
'./render/texturizerBullseye'
], 
function(){})